name: build_apk

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  workflow_dispatch:
    inputs:
      sniffer:
        description: Use sniffer(proxy)
        type: boolean
        required: false
        default: false
      comment:
        description: Msg to chat Slack(ss-devapp)
        required: false
      host:
        description: Host
        required: false
        default: https://lahta.uat.simple-solution.liis.su/api
      api_version:
        description: api version
        default: v1

jobs:
  build-android:
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v3
        - name: yarn
          run: |
            yarn
        - name: Make gradlew executable
         run: chmod +x ./gradlew
        - name: Build Android Release
          run: |
            export CUSTOM_HOST=${{ inputs.host }}
            export API_VERSION=${{ inputs.api_version }}
            export IS_PROXY_ENABLED=${{ inputs.sniffer }}
            cd android && ./gradlew assembleRelease
        - name: Upload Artifact
          uses: actions/upload-artifact@v1
          with:
            name: app-release.apk
            path: android/app/build/outputs/apk/release/app-release.apk

