name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  pull_request:
    branches:
      - 'main'


jobs:
  build_apk:
    name: Run build apk on PR in main
    runs-on: ubuntu-20.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Run unit tests
        run: echo Run unit tests

      - name: build apk
        run: echo build apk gradle